services:
  db:
    build: ./database
    container_name: film_checker_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_PORT: ${POSTGRES_PORT}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - film_checker_front_back_network

  backend:
    build: ./backend
    container_name: film_checker_backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    depends_on:
      - db
    networks:
      - film_checker_back_db_network
      - film_checker_front_back_network

  frontend:
    build: ./frontend
    container_name: film_checker_frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - film_checker_back_db_network

volumes:
  postgres_data:

networks:
  film_checker_front_back_network:
    driver: bridge
  film_checker_back_db_network:
    driver: bridge