services:
  db:
    image: nonouille/watchlist_provider_database:latest
    container_name: film_checker_db
    restart: unless-stopped
    env_file: .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_PORT: ${POSTGRES_PORT}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - film_checker_front_back_network

  backend:
    image: nonouille/watchlist_provider_backend:latest
    container_name: film_checker_backend
    restart: unless-stopped
    env_file: .env
    environment:
      TMDB_TOKEN: ${TMDB_TOKEN}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
    ports:
      - "5000:5000"
    depends_on:
      - db
    networks:
      - film_checker_back_db_network
      - film_checker_front_back_network

  frontend:
    image: nonouille/watchlist_provider_frontend:latest
    container_name: film_checker_frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - film_checker_back_db_network

  datadog:
    image: datadog/agent:latest
    container_name: datadog-agent
    restart: unless-stopped
    env_file: .env
    environment:
      DD_API_KEY: ${DD_API_KEY}
      DD_SITE: ${DD_SITE}
      DD_APM_ENABLED: "true"
      DD_LOGS_ENABLED: "true"
      DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL: "true"
      DD_CONTAINER_EXCLUDE: "name:datadog-agent"
      DD_CONTAINER_INCLUDE: "name:film_checker_db name:film_checker_backend name:film_checker_frontend"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro
    networks:
      - film_checker_front_back_network
      - film_checker_back_db_network

volumes:
  postgres_data:

networks:
  film_checker_front_back_network:
    driver: bridge
  film_checker_back_db_network:
    driver: bridge
