version: '3.8'

services:
  db:
    image: postgres:15
    container_name: film_checker_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: checklist
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    container_name: film_checker_backend
    restart: unless-stopped
    environment:
      DB_HOST: db
      DB_NAME: checklist
      DB_USER: postgres
      DB_PASSWORD: ${DB_PASSWORD}
      DB_PORT: 5432
    ports:
      - "5000:5000"
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: film_checker_frontend
    restart: unless-stopped
    ports:
      - "80:3000"
    depends_on:
      - backend

volumes:
  postgres_data: