name: Deploy After Success

on:
  push:
    branches:
      - main
  workflow_run:
    workflows: ["Docker Backend Image CD", "Docker Frontend Image CD", "Docker Database Image CD"]
    types:
      - completed

jobs:
  deploy:
    # if: ${{ github.event.workflow_run.conclusion == 'success' }}
    environment: Docker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Connect to Server and Deploy
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
        run: |
          ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST << 'EOF'
          cd /home/arnaud/watchlist_providers/
          docker-compose down
          docker system prune -f
          docker-compose up -d --build
          EOF
